- hosts: win_srvs
  gather_facts: true
  tasks:
############# Gather Facts ####################
  - name: Gather C-Drive
    ansible.windows.win_powershell:
     script: |
      Get-Partition -DriveLetter C | Select-Object -ExpandProperty Size | ForEach-Object {[Math]::Ceiling($_ / 1GB)}
    register: cdrive
    tags: base

########## WSUS ###########################
  - name: Set Group Policy
    ansible.windows.win_group:
      name: WSUS
      policy_id: SpecifyIntranetLocation
      policy_type: Machine
      state: enabled
      registry_key: HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate
      registry_value: WUServer
      registry_data: http://10.16.0.33:8530
